name: Generate Android Keystore

on:
  workflow_dispatch:
  push:
    branches:
      - kosmos-design
    paths:
      - ".github/workflows/generate-android-keystore.yml"

jobs:
  generate-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Generate keystore
        run: |
          mkdir -p output
          keytool -genkeypair -v \
            -keystore output/kosmos-vpn-release.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias kosmosvpn \
            -storepass "${{ secrets.TEMP_KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.TEMP_KEY_PASSWORD }}" \
            -dname "CN=Kosmos VPN, OU=Kosmos VPN, O=Kosmos VPN, L=Rostov-on-Don, S=Rostov, C=RU"

      - name: Create base64 copy
        run: |
          base64 -w 0 output/kosmos-vpn-release.jks > output/kosmos-vpn-release-base64.txt

      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: kosmos-vpn-release-keystore
          path: output/
          retention-days: 1
