name: Kosmos APK Release

on:
  workflow_dispatch:
  push:
    branches:
      - kosmos-design
    paths:
      - ".github/workflows/kosmos-apk.yml"
      - "android/**"
      - "assets/**"
      - "lib/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - "Makefile"
      - "dependencies.properties"

env:
  IS_GITHUB_ACTIONS: 1
  CHANNEL: dev
  SENTRY_DSN: ""

jobs:
  build-android-release-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Clean disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: "3.38.5"
          channel: "stable"
          cache: true

      - name: Check Flutter version
        run: flutter --version

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install project dependencies
        run: flutter pub get

      - name: Prepare Hiddify Android project
        run: make android-apk-prepare

      - name: Build release APK
        run: flutter build apk --release --target lib/main.dart --dart-define=SENTRY_DSN=""

      - name: Rename APK
        run: |
          mkdir -p output
          cp build/app/outputs/flutter-apk/app-release.apk output/Kosmos-VPN-Android-v4.1.3.apk
          ls -lah output/

      - name: Upload APK to GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kosmos-VPN-Android-v4.1.3-apk
          path: output/Kosmos-VPN-Android-v4.1.3.apk
          retention-days: 7

      - name: Send APK to Telegram
        continue-on-error: true
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -F document="@output/Kosmos-VPN-Android-v4.1.3.apk" \
            -F caption="🚀 Новая сборка Космос VPN v4.1.3 готова"
